sudo: false
language: ruby
cache: bundler
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
  - jruby-head
  - jruby-9.2.9.0
  - truffleruby
before_install:
  - gem install bundler -v 1.17.3
git:
  submodules: false
gemfile:
  - Gemfile
matrix:
  include:
    - rvm: 2.5
      gemfile: gemfiles/rubyracer
    - rvm: jruby-9.2.9.0
      gemfile: gemfiles/rubyrhino
    - rvm: jruby-head
      gemfile: gemfiles/rubyrhino
    - rvm: 2.5
      gemfile: gemfiles/alaska
      env: ALASKA=1
  allow_failures:
    - rvm: 2.5
      gemfile: gemfiles/alaska
      env: ALASKA=1
    - rvm: ruby-head
    - rvm: truffleruby
    - rvm: jruby-head
    - rvm: jruby-head
      gemfile: gemfiles/rubyrhino
  fast_finish: true
