name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 1.9.3
          - 2.0.0
          - 2.1.10
          - 2.2.10
          - 2.3.8
          - 2.4.6
          - 2.5.5
          - 2.6.3
          - jruby-9.2.8.0
    steps:
      - uses: actions/checkout@v1
      - name: Set up RVM
        run: |
          curl -sSL https://get.rvm.io | bash
      - name: Set up Ruby
        run: |
          source $HOME/.rvm/scripts/rvm
          rvm install ${{ matrix.ruby }}
          rvm --default use ${{ matrix.ruby }}
      - name: Build and test with Rake
        run: |
          source $HOME/.rvm/scripts/rvm
          gem install bundler -v 1.17.3
          bundle install --jobs 4 --retry 3
          bundle exec rake spec
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: lautis/rubocop-action@master
        name: Lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
